cmake_minimum_required(VERSION 3.0.2)
project(five_ugv_mpc_formation_control)
find_package(catkin REQUIRED COMPONENTS five_ugv_formation_control rospy geometry_msgs nav_msgs std_msgs)
catkin_python_setup()
catkin_package()
catkin_install_python(PROGRAMS scripts/mpc_follower.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config launch DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
