tag_height: 0.25
valid_max_residual_rms: 0.6
anchors:
- id: 0
  x: 0.0
  y: 0.0
  z: 1.35
- id: 4
  x: 2.988
  y: 0.142
  z: 1.35
- id: 1
  x: 6.263
  y: 0.501
  z: 1.35
- id: 2
  x: 6.095
  y: 4.651
  z: 1.35
- id: 5
  x: 3.086
  y: 4.374
  z: 1.35
- id: 3
  x: 0.0
  y: 4.275
  z: 1.35
